# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.FloatField(blank=True, max_length=6, null=True)),
                ('camera', models.CharField(choices=[('SLR', 'SLR'), ('Range finder', 'Range finder'), ('Twin reflex', 'Twin reflex')], max_length=15)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('WEDDING', 'Wedding'), ('PAPARAZZI', 'Paparazzi')], max_length=17)),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('photo_style', multiselectfield.db.fields.MultiSelectField(choices=[('BLACK AND WHITE', 'Black and White'), ('COLOR', 'Color'), ('PHOTOSHOP', 'Photoshop')], max_length=31)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
