# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 01:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
                ('profile', django.db.models.manager.Manager()),
            ],
        ),
    ]
