# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
