# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 22:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171128_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BLACK AND WHITE', 'Black and White'), ('COLOR', 'Color'), ('PHOTOSHOP', 'Photoshop')], max_length=31),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('WEDDING', 'Wedding'), ('PAPARAZZI', 'Paparazzi')], max_length=17),
        ),
    ]
