# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20171130_0152'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
            ],
        ),
    ]
