# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0006_auto_20171204_2054'),
        ('imager_profile', '0003_auto_20171128_2236'),
    ]

    operations = [
    ]
