# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0007_merge_20171204_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=models.CharField(choices=[('BLACK AND WHITE', 'Black and White'), ('COLOR', 'Color'), ('PHOTOSHOP', 'Photoshop')], max_length=20),
        ),
    ]
