# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_tile',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(to='imager_images.Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
