# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20171129_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(to='imager_images.Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='django_imager/MEDIA'),
        ),
    ]
