# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20171129_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
    ]
