# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20171127_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='date_published',
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
    ]
