# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20171129_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(null=True, upload_to='django_imager/MEDIA'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(upload_to='django_imager/MEDIA'),
        ),
    ]
