# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20171127_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_tile',
            new_name='album_title',
        ),
    ]
