# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 01:13
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20171130_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='django_imager/MEDIA'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=sorl.thumbnail.fields.ImageField(upload_to='django_imager/MEDIA'),
        ),
    ]
