# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20171127_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
